---
title: "Article Summary"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

  In the paper, “Does One Year of Schooling Improve Children’s Cognitive Control and Alter Associated Brain Activation?” scientists investigated the direct consequence of schooling on the brain network essential to cognitive control. The “5-to-7-year shift” refers to significant developments in children’s cognitive abilities, especially the ability to control their own attention and behavior, that occur when they are between 5-7 years of age. It is believed that schooling plays a significant role in this development as 5-7 years old is when most children start school. Going to school means paying attention in class and learning to sit still, as compared to before, when most of their education was oriented towards play and greater activity.
  
  Executive functions (EFs) are divided into 3 categories: inhibitory control, working memory, & cognitive flexibility. The researchers hypothesized that over the year, EFs (especially inhibitory control), would develop for both groups because of brain maturation, as well as amplified engagement of frontoparietal control regions, specifically, ventrolateral and dorsolateral prefrontal cortex and posterior parietal cortex. They also tested 3 alternative hypotheses concerning the relationship between formal school and changes in EFs: (1) formal schooling amplifies these behavioral & neural changes, (2) its consequences differ across varying features of the task as well as varying regions of the brain, (3) it has no further effect over & above the effects of changes related to age.
  
  The study endured for 2 consecutive summers in Berlin and involved 5-to-6-year-old children. Each child participated in 3 test sessions/year on varying days. During the pretest measurement, all children were in kindergarten, while during the posttest measurement, some had attended almost the entire first grade year, while others continued with kindergarten. Kindergarten was more play-oriented, while all first-grade classes followed a structured, federally-determined curriculum. The sessions were 90 minutes long, with a behavioral component and a neuroimaging component.

  The hearts-and-flowers task (HFT) took place at a desktop computer during the first of the 3 testing sessions/year. It comprised 3 conditions, with 20 trials/block. In the first block (congruent condition), the children were presented with a heart on every trial and instructed to press the button on the same side that the heart was on. In the second block (incongruent condition), the children were presented with a flower and instructed to press the button on the side opposite to the one with the flower (requires inhibitory control). In the third block (mixed condition), the same rules applied, except the children were presented with both hearts and flowers (requires cognitive flexibility). This task required preservation of task rules in working memory, along with prolonged attention to the arrangement of trials. 

  The cats-and-dogs (independent) task (CDT) was performed in the MRI scanner during the third of the 3 testing sessions/year. When presented with a picture of a dog, the children had to press a button with their right index finger (go condition). If it was a cat, they had to withhold this response (no-go condition). Go trials were presented 3 times more than no-go trials, with the order of presentation of these trials being pseudorandom. This task also required prolonged attention to encrypt the appearance of stimuli, as well as working memory to remember to press a button in response to dogs only. The no-go condition required response inhibition so as not to press the button when a cat appeared on the screen. 
  
  The researchers found that: (1) first graders performed better overall than kindergartners in all task conditions, (2) task performance progressed from pretest to posttest, (3) children performed best on congruent trials & worst on mixed trials, (4) first graders showed greater task improvement than kindergartners, (5) greater improvement was seen in the incongruent & mixed conditions compared to the congruent condition.
  
  The HFT results supported that schooling led to a general increase in accuracy in all the conditions. The CDT results showed that performance was improved at posttest, and this improvement was independent of schooling. The pretest fMRI results indicate no difference between the two groups’ activation during correct no-go trials. For correct-go trials, however, there were significant group differences, with first-graders showing greater activation in bilateral superior PPC. Left superior PPC displayed a schooling effect, unrelated to group differences. This region’s analyses showed a specific effect of schooling in the superior PPC during correct go trials. Follow-up analyses detected an increase in activation for go trials in a right superior PPC cluster, stronger for first graders than kindergartners at posttest (after attending 1 year of school). 
  
  There was a significant positive correlation between increase in PPC activation & CDT performance and between increase in PPC activation & HFT performance from pretest to posttest. Children who had experienced formal schooling exhibited greater HFT accuracy, and therefore greater improvement in EFs. Brain activation patterns during CDT depicted both groups exhibiting an increase in right superior PPC activation during correct go trials across one year (larger for first graders). Increase in PPC activation during the CDT was correlated with better performance on the HFT, therefore supporting the hypothesis that formal education contributes to age-related increases in EFs and magnifies these behavioral and neural changes.
  
  The researchers concluded that early schooling, which requires prolonged attention, leads to greater accuracy on a task that demands greater attention, as well as to increased engagement of the PPC. Despite the fact that EFs are highly heritable, it was found that they can be shaped by exposure to a structured learning environment. 
