---
title: "Reproducing ANOVA Analysis"
output: html_document
---

### R and R-Studio

```{r}
library(data.table)
rftsample <- fread("CopyOfnogo_flowheart_R.csv")
```

```{r}
library(dplyr)


exclude_IDS <- rftsample[is.na(rftsample$rt_go) == TRUE, ]$ID


reaction_time <- rftsample %>%
                    filter(ID %in% exclude_IDS == FALSE) %>%
                    group_by(group,Time) %>%
                    summarise(reaction_time = mean(rt_go))

library(ggplot2)

ggplot(reaction_time, aes(x=group,
                            y=reaction_time,
                            group=Time,
                            fill=Time))+
  geom_bar(stat="identity",position="dodge")

```

```{r}
anova_data <- rftsample %>%
                    filter(ID %in% exclude_IDS == FALSE) %>%
                    mutate(ID = as.factor(ID),
                           group = as.factor(group),
                           Time = as.factor(Time))

aov.out <- aov(rt_go ~ group*Time + Error(ID/Time), anova_data)
summary(aov.out)
```

```{r}
print(model.tables(aov.out,"means"), format="markdown")

```

