<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>Reproducible Statistical Analysis</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">NoorProject</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="Journal.html">R Basics</a>
</li>
<li>
  <a href="Links.html">Reproducible Statistical Analysis</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Reproducible Statistical Analysis</h1>

</div>


<div id="article-summary" class="section level3">
<h3>Article Summary</h3>
<p>In the paper, “Does One Year of Schooling Improve Children’s Cognitive Control and Alter Associated Brain Activation?” scientists investigated the direct consequence of schooling on the brain network essential to cognitive control. The “5-to-7-year shift” refers to significant developments in children’s cognitive abilities, especially the ability to control their own attention and behavior, that occur when they are between 5-7 years of age. It is believed that schooling plays a significant role in this development as 5-7 years old is when most children start school. Going to school means paying attention in class and learning to sit still, as compared to before, when most of their education was oriented towards play and greater activity.</p>
<p>Executive functions (EFs) are divided into 3 categories: inhibitory control, working memory, &amp; cognitive flexibility. The researchers hypothesized that over the year, EFs (especially inhibitory control), would develop for both groups because of brain maturation, as well as amplified engagement of frontoparietal control regions, specifically, ventrolateral and dorsolateral prefrontal cortex and posterior parietal cortex. They also tested 3 alternative hypotheses concerning the relationship between formal school and changes in EFs: (1) formal schooling amplifies these behavioral &amp; neural changes, (2) its consequences differ across varying features of the task as well as varying regions of the brain, (3) it has no further effect over &amp; above the effects of changes related to age.</p>
<p>The study endured for 2 consecutive summers in Berlin and involved 5-to-6-year-old children. Each child participated in 3 test sessions/year on varying days. During the pretest measurement, all children were in kindergarten, while during the posttest measurement, some had attended almost the entire first grade year, while others continued with kindergarten. Kindergarten was more play-oriented, while all first-grade classes followed a structured, federally-determined curriculum. The sessions were 90 minutes long, with a behavioral component and a neuroimaging component.</p>
<p>The hearts-and-flowers task (HFT) took place at a desktop computer during the first of the 3 testing sessions/year. It comprised 3 conditions, with 20 trials/block. In the first block (congruent condition), the children were presented with a heart on every trial and instructed to press the button on the same side that the heart was on. In the second block (incongruent condition), the children were presented with a flower and instructed to press the button on the side opposite to the one with the flower (requires inhibitory control). In the third block (mixed condition), the same rules applied, except the children were presented with both hearts and flowers (requires cognitive flexibility). This task required preservation of task rules in working memory, along with prolonged attention to the arrangement of trials.</p>
<p>The cats-and-dogs (independent) task (CDT) was performed in the MRI scanner during the third of the 3 testing sessions/year. When presented with a picture of a dog, the children had to press a button with their right index finger (go condition). If it was a cat, they had to withhold this response (no-go condition). Go trials were presented 3 times more than no-go trials, with the order of presentation of these trials being pseudorandom. This task also required prolonged attention to encrypt the appearance of stimuli, as well as working memory to remember to press a button in response to dogs only. The no-go condition required response inhibition so as not to press the button when a cat appeared on the screen.</p>
<p>The researchers found that: (1) first graders performed better overall than kindergartners in all task conditions, (2) task performance progressed from pretest to posttest, (3) children performed best on congruent trials &amp; worst on mixed trials, (4) first graders showed greater task improvement than kindergartners, (5) greater improvement was seen in the incongruent &amp; mixed conditions compared to the congruent condition.</p>
<p>The HFT results supported that schooling led to a general increase in accuracy in all the conditions. The CDT results showed that performance was improved at posttest, and this improvement was independent of schooling. The pretest fMRI results indicate no difference between the two groups’ activation during correct no-go trials. For correct-go trials, however, there were significant group differences, with first-graders showing greater activation in bilateral superior PPC. Left superior PPC displayed a schooling effect, unrelated to group differences. This region’s analyses showed a specific effect of schooling in the superior PPC during correct go trials. Follow-up analyses detected an increase in activation for go trials in a right superior PPC cluster, stronger for first graders than kindergartners at posttest (after attending 1 year of school).</p>
<p>There was a significant positive correlation between increase in PPC activation &amp; CDT performance and between increase in PPC activation &amp; HFT performance from pretest to posttest. Children who had experienced formal schooling exhibited greater HFT accuracy, and therefore greater improvement in EFs. Brain activation patterns during CDT depicted both groups exhibiting an increase in right superior PPC activation during correct go trials across one year (larger for first graders). Increase in PPC activation during the CDT was correlated with better performance on the HFT, therefore supporting the hypothesis that formal education contributes to age-related increases in EFs and magnifies these behavioral and neural changes.</p>
<p>The researchers concluded that early schooling, which requires prolonged attention, leads to greater accuracy on a task that demands greater attention, as well as to increased engagement of the PPC. Despite the fact that EFs are highly heritable, it was found that they can be shaped by exposure to a structured learning environment.</p>
</div>
<div id="reproducing-anova-analysis" class="section level3">
<h3>Reproducing ANOVA Analysis</h3>
<pre class="r"><code>library(data.table)
rftsample &lt;- fread(&quot;CopyOfnogo_flowheart_R.csv&quot;)</code></pre>
<pre class="r"><code>library(dplyr)</code></pre>
<pre><code>## 
## Attaching package: &#39;dplyr&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:data.table&#39;:
## 
##     between, first, last</code></pre>
<pre><code>## The following objects are masked from &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## The following objects are masked from &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<pre class="r"><code>exclude_IDS &lt;- rftsample[is.na(rftsample$rt_go) == TRUE, ]$ID


reaction_time &lt;- rftsample %&gt;%
                    filter(ID %in% exclude_IDS == FALSE) %&gt;%
                    group_by(group,Time) %&gt;%
                    summarise(reaction_time = mean(rt_go))

library(ggplot2)</code></pre>
<pre><code>## Registered S3 methods overwritten by &#39;ggplot2&#39;:
##   method         from 
##   [.quosures     rlang
##   c.quosures     rlang
##   print.quosures rlang</code></pre>
<pre class="r"><code>ggplot(reaction_time, aes(x=group,
                            y=reaction_time,
                            group=Time,
                            fill=Time))+
  geom_bar(stat=&quot;identity&quot;,position=&quot;dodge&quot;)</code></pre>
<p><img src="Links_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<pre class="r"><code>anova_data &lt;- rftsample %&gt;%
                    filter(ID %in% exclude_IDS == FALSE) %&gt;%
                    mutate(ID = as.factor(ID),
                           group = as.factor(group),
                           Time = as.factor(Time))

aov.out &lt;- aov(rt_go ~ group*Time + Error(ID/Time), anova_data)
summary(aov.out)</code></pre>
<pre><code>## 
## Error: ID
##           Df  Sum Sq Mean Sq F value Pr(&gt;F)
## group      1   22842   22842   1.016  0.318
## Residuals 56 1258643   22476               
## 
## Error: ID:Time
##            Df Sum Sq Mean Sq F value   Pr(&gt;F)    
## Time        1  69146   69146   12.53 0.000813 ***
## group:Time  1   1489    1489    0.27 0.605386    
## Residuals  56 308934    5517                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>print(model.tables(aov.out,&quot;means&quot;), format=&quot;markdown&quot;)</code></pre>
<pre><code>## Tables of means
## Grand mean
##        
## 792.67 
## 
##  group 
##         2     3
##     811.3 782.1
## rep  42.0  74.0
## 
##  Time 
##         1     2
##     817.1 768.3
## rep  58.0  58.0
## 
##  group:Time 
##      Time
## group 1     2    
##   2   840.5 782.1
##   rep  21.0  21.0
##   3   803.8 760.4
##   rep  37.0  37.0</code></pre>
</div>
<div id="re-analysis-discussion" class="section level3">
<h3>Re-Analysis Discussion</h3>
<p>We attempted to reproduce a 2x2 mixed-design ANOVA analysis for reaction time versus group of the cats-and-dogs task (CDT). After uploading the data to R, it was observed that R was treating the numbers as letters so all commas were replaced with periods. Then, this data was added into our global environment/library. Certain subjects (ID) had to be excluded from the data set because they had “NAs” or “NAN,” leaving us with 56 of the initial 60 subjects. The data was then grouped based on Time (i.e. posttest and pretest) and group (kindergartners and first graders) and then used ggplot2 to create a bar graph of reaction_time versus group. ID, group, and Time were mutated to become factors, as they were integers before. The ANOVA code for mixed design was used. The dependent variable was rt_go, the independent variable for between subjects was group and Time was the independent variable for within subjects. The summary tool was used to depict the re-analysis values. There was no significant interaction effect between group and Time: F(1,56)=0.27, p=0.61, p&gt;0.05. A significant main effect of Time was found: F(1,56)=12.53, p=0.00081, p&lt;0.05. There was no significant main effect for group: F(1,56)=1.016, p=0.32, p&gt;0.05. These numbers do not match exactly with the results in the paper. This is because the researchers excluded several other subjects so that there were only 53 rather than 56. Although these numbers do not match with the ones in the paper, they produce the same results (i.e. no significant interaction, significant main effect for Time, no significant main effect for group) as those stated on page 973 when discussing the mixed-design ANOVA on reaction times for correct go trials.</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
